name: INI-T-Bot

on:
  workflow_dispatch:      # 允许手动触发

jobs:
  auto-process:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # 使用你设置的 secret

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create directories
        run: |
          mkdir -p Python/output
          mkdir -p Python/downloads

      - name: Install dependencies
        run: |
          cd Python
          pip install -r requirements.txt

      - name: Get SCREEN NAME
        id: get-user-id
        env:
          REDIS_CONFIG: ${{ secrets.REDIS_CONFIG }}
        run: |
          cd Python/src
          SCREEN_NAME=$(python redis_screen_name.py)
          echo "SCREEN_NAME=$SCREEN_NAME" >> $GITHUB_ENV

      - name: Run X-Bot.py
        run: |
          cd Python/src
          python X-Bot.py "../../TypeScript/tweets/user/$SCREEN_NAME.json"

      - name: Run T-Bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          LARK_KEY: ${{ secrets.LARK_KEY }}
        run: |
          cd Python/src
          python T-Bot.py

      - name: Upload Response Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: network-responses-${{ github.run_id }}  # 唯一标识
          path: |
            TypeScript/resp/
            TypeScript/logs/
            Python/logs/
          retention-days: 7  # 自动清理

      - name: Commit and push changes
        run: |
          git add Python/output Python/dataBase TypeScript/tweets
          git commit -m "chore: update user data [skip ci]" || exit 0
          git push
